import fs from 'node:fs/promises';
const path='src/components/onboarding-editor.tsx';let s=await fs.readFile(path,'utf8');s=s.replace("import {Button} from './ui/button';","import {Button} from './ui/button';\nimport {AccountSelect} from './account-select';");
const start=s.indexOf(' const select=');const end=s.indexOf('\n async function save',start);s=s.slice(0,start)+` const select=(label:string,key:keyof AccountProfile,options:[string,string][],required=false)=><AccountSelect label={label} value={String(p[key])} options={options} required={required} onChange={value=>update(key,value)}/>;
 const detail=(label:string,key:string,placeholder:string,required=true)=><label className="account-field">{label}{required&&<span> *</span>}<input value={p.details[key]||''} required={required} placeholder={placeholder} onChange={e=>update('details',{...p.details,[key]:e.target.value})}/></label>;
 const professionalFields=()=>{switch(p.professionalCategory){case 'startup':return <>{field('Startup Name','organization','Enter startup name',true)}{field('Startup Website','website','https://yourstartup.com',false,'url')}<label className="account-field account-field-wide">Elevator Pitch<textarea value={p.pitch} onChange={e=>update('pitch',e.target.value)} placeholder="Describe your startup in a few sentences..."/></label></>;case 'corporate':return <>{field('Company Name','organization','Enter company name',true)}{field('Role','jobTitle','Enter your role',true)}</>;case 'self_employed':return <label className="account-field account-field-wide">Service Offerings<textarea value={p.details.serviceOfferings||''} onChange={e=>update('details',{...p.details,serviceOfferings:e.target.value})} placeholder="Enter your services separated by commas (e.g., Web Development, UI/UX Design, Consulting)"/></label>;case 'venture_capitalist':case 'investor':return <>{p.professionalCategory==='venture_capitalist'&&field('Company Name','organization','Enter company name',true)}{detail('Investment Sector','investmentSector','Enter investment sector')}{detail('Fund Size','fundSize','Enter fund size (e.g., 1,000,000.00)')}</>;case 'accelerator':case 'university':case 'government':case 'non_profit':return <>{field(['accelerator','university'].includes(p.professionalCategory)?'Institution Name':'Organization Name','organization',['accelerator','university'].includes(p.professionalCategory)?'Enter institution name':'Enter organization name',true)}{['accelerator','non_profit'].includes(p.professionalCategory)?detail('Focus Sector','focusSector','Enter focus sector'):field('Designation','jobTitle','Enter designation',true)}</>;default:return null;}}
`+s.slice(end);
const begin=s.indexOf("select('Professional Category'");const finish=s.indexOf('</>}</div><label className="account-field account-upload-label">',begin);
s=s.slice(0,begin)+`select('Professional Category','professionalCategory',[['corporate','Corporate'],['startup','Startup'],['self_employed','Self-Employed'],['venture_capitalist','Venture Capitalist'],['investor','Investor'],['accelerator','Accelerator'],['university','University'],['government','Government'],['non_profit','Non-Profit'],['other','Other']],true)}<div/>{professionalFields()}`+s.slice(finish);
await fs.writeFile(path,s);
